version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  postgres:
    image: ankane/pgvector:latest
    volumes:
      - C:\Users\yepis\dev\postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres    
      POSTGRES_DB: cybercore_db 
    command:
      - postgres
      - -c
      - "shared_preload_libraries='pgvector'"
      - -c
      - "max_connections=200"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cybercore_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  init-db:
    image: postgres:latest
    depends_on:
      - postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cybercore_db