spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cybercore_db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9092
  profiles:
    active: docker

server:
  port: 8080